version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_NAME=perfectsite
      - DB_USER=pavel
    depends_on:
      - db

  redis:
    container_name: "myredis"
    image: "redis"
    command: redis-server --port 6379
    ports:
      - "6379:6379"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"